# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
anchors:
  container-config: &container-config
      docker:
        - image: circleci/node:10.15
          environment:
            TERM: dumb
  configure-aws-access: &configure-aws-access
      run:
        name: Configure AWS access
        command: |
          mkdir -p ~/.aws
          cat > ~/.aws/credentials << EOL
          [default]
          aws_access_key_id = ${ACCESS_KEY_ID}
          aws_secret_access_key = ${SECRET_ACCESS_KEY}
          EOL
  cache-dependencies: &cache-dependencies
    save_cache:
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - node_modules

  load-dependency-cache: &load-dependency-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  
  prod-config: &prod-config
    environment:
      - STAGE: prod

  deploy: &deploy
    <<: *container-config
    steps:
      - checkout
      - *load-dependency-cache
      - *configure-aws-access
      - run:
          name: Deploy application
          command: sls deploy -v

version: 2
jobs:
  install:
    <<: *container-config
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - *load-dependency-cache
      - run:
          name: Install Node dependencies
          command: npm i
      - run:
          name: Install Python dependencies
          command: |
            sudo apt install software-properties-common
            sudo bash -c "yes | add-apt-repository ppa:deadsnakes/ppa && add-apt-repository -r ppa:deadsnakes/ppa && apt-get update && apt-get install -y python3.6"
            sudo apt-get install python3-venv
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - *cache-dependencies
  deploy-prod:
    <<: *deploy
    <<: *prod-config

workflows:
  version: 2

  deploy-pipeline:
    jobs:
      - install
      - deploy-prod:
          context: ny-doorman
          requires:
            - install