# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
anchors:
  container-config: &container-config
      docker:
        - image: circleci/node:10.15
          environment:
            TERM: dumb
  configure-aws-access: &configure-aws-access
      run:
        name: Configure AWS access
        command: |
          mkdir -p ~/.aws
          cat > ~/.aws/credentials << EOL
          [default]
          aws_access_key_id = ${ACCESS_KEY_ID}
          aws_secret_access_key = ${SECRET_ACCESS_KEY}
          EOL
  cache-dependencies: &cache-dependencies
    save_cache:
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - node_modules

  load-dependency-cache: &load-dependency-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  
  prod-config: &prod-config
    environment:
      - STAGE: prod

  deploy: &deploy
    <<: *container-config
    steps:
      - checkout
      - *load-dependency-cache
      - *configure-aws-access
      - run:
          name: Deploy application
          command: npm run deploy

version: 2
jobs:
  install-deploy:
    <<: *container-config
    environment:
      STAGE: prod
    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: Install Node dependencies
          command: npm i
      # - *cache-dependencies
      - *configure-aws-access
      - run:
          name: Deploy application
          command: npm run deploy
      

  # deploy-prod:
  #   <<: *deploy
  #   <<: *prod-config

workflows:
  version: 2

  deploy-pipeline:
    jobs:
      - install-deploy:
          context: ny-doorman
      # - deploy-prod:
      #     context: ny-doorman
      #     requires:
      #       - install